### ISSUE TITLE
Way of contact

### ISSUE THREAD

**Issue by Henrimn** [LiamAshdown/Darkorbit-Emulator#2]
Hello,

I'm very interested in your work and would like to discuss more with you regarding it. However, I don't know how to contact you besides github, so I have hope that you will be notified by this. If you are interested and want to give it a try, please send me a message through discord: Henri#0024 or leave me your email here.

Hope to hear from you soon.

**Comment by LiamAshdown** [comment]
Hi there,

I've sent you a friend request on Discord.
